import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { NextAuthProvider } from "./components/NextAuthProvider";


const inter = Nunito({ 
  subsets: ["latin"] });

export const metadata: Metadata = {
  title: "iFilm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
        {children}
        </NextAuthProvider>
        </body>
    </html>
  );
}
